approvalsys/config/routes.rb
Rails.application.routes.draw do
  get 'vue/index'

  resources :appls

  #ホーム画面
  get "static_pages/home"

  #共通画面（ヘッダー、フッター、メニュー）
  get "static_pages/common"

  #システム管理者
  #mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  #初期表示画面指定
  root "static_pages#home"

  #DEVICE設定
  devise_for :users, :controllers => {
                       :registrations => "users/registrations",
                       :sessions => "users/sessions",
                     }

  devise_scope :user do
    #ログイン
    get "sign_in", :to => "users/sessions#new"
    #ログアウト
    get "sign_out", :to => "users/sessions#destroy"
    #アカウント作成
    get "sign_up", :to => "users/registrations#new"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 確認ページ
  resources :appls do
    collection do
      post "confirm"
    end
  end

  # ユーザー管理ページ
  resources :users do
    collection do
      post "confirm"
    end
  end

  #エラーページ
  get "*path", controller: "application", action: "render_403"
  get "*path", controller: "application", action: "render_404"
  get "*path", controller: "application", action: "render_500"

  get "vue/index", controller: "vue", action: "index"
end

approvalsys/app/models/appl.rb
class Appl < ApplicationRecord
end

approvalsys/app/controllers/appls_controller.rb
class ApplsController < ApplicationController
  before_action :set_appl, only: [:show, :edit, :update, :destroy]

  layout "common"

  # GET /appls
  def index
    @appls = Appl.all
  end

  # GET /appls/1
  def show
  end

  # GET /appls/new
  def new
    @appl = Appl.new
  end

  # GET /appls/1/edit
  def edit
  end

  # POST /appls
  def create
    @appl = Appl.new(appl_params)

    if @appl.save
      # redirect_to @appl, notice: "Appl was successfully created."
      render json: { status: 'SUCCESS', message: 'loaded the post', data: @appl }
    else
      # render :new
      render json: { status: 'ERROR', message: 'post not saved', data: @appl.errors }
    end
  end

  # PATCH/PUT /appls/1
  def update
    if @appl.update(appl_params)
      render json: { status: 'SUCCESS', message: 'loaded the post', data: @appl }
    else
      ender json: { status: 'ERROR', message: 'post not saved', data: @appl.errors }
    end
  end

  # DELETE /appls/1
  def destroy
    @appl.destroy
    redirect_to appls_url, notice: "Appl was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appl
    @appl = Appl.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def appl_params
    params.require(:appl).permit(:user_id, :title, :state, :description, :checked)
  end
end

approvalsys/app/helpers/appls_helper.rb
module ApplsHelper
end

approvalsys/app/views/appls/_form.html.erb
<%= form_with(model: appl, local: true) do |form| %>
<!-- Main content -->
<section class="content">
  <!--------------------------
     | Your Page Content Here |
    -------------------------->
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <br/>
        <!-- /.box-header -->
        <div class="box-body">
          <% if appl.errors.any? %>
          <p>
            <div id="error_explanation" class="alert alert-danger alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <% appl.errors.full_messages.each do |message| %>
              <ul>
                <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </p>
          <% end %>
                      <div class="form-group">
                              <%= form.label :user_id %><br />
                <%= form.text_field :user_id, id: :appl_user_id, class: "form-control" %>
                          </div>
                      <div class="form-group">
                              <%= form.label :title %><br />
                <%= form.text_field :title, id: :appl_title, class: "form-control" %>
                          </div>
                      <div class="form-group">
                              <%= form.label :state %><br />
                <%= form.number_field :state, id: :appl_state, class: "form-control" %>
                          </div>
                      <div class="form-group">
                              <%= form.label :description %><br />
                <%= form.text_area :description, id: :appl_description, class: "form-control" %>
                          </div>
                    <div class="box-footer actions">
            <%= link_to '戻る', appls_path, class: 'btn btn-primary' %>
            <%= form.submit '更新', class: "btn btn-primary pull-right" %>
          </div>
        </div>
        <!-- /.box-body -->
      </div>
    </div>
  </div>
</section>
<% end %>

approvalsys/app/views/appls/edit.html.erb
<section class="content-header">
  <h1>Appl変更</h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
    <li class="active">Here</li>
  </ol>
</section>
<%= render 'form', appl: @appl %>

approvalsys/app/views/appls/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Appls一覧</h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
    <li class="active">Here</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">
            <%= link_to '新規', new_appl_path, class: 'btn btn-primary' %>
          </h3>
          <div class="box-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
              <div class="input-group-btn">
                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <thead>
              <tr>
                                  <th>User</th>
                                  <th>Title</th>
                                  <th>State</th>
                                  <th>Description</th>
                                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              <% @appls.each do |appl| %>
              <tr>
                                  <td><%= appl.user_id %></td>
                                  <td><%= appl.title %></td>
                                  <td><%= appl.state %></td>
                                  <td><%= appl.description %></td>
                                <td>
                  <div class="btn-group">
                    <%= link_to '表示', appl, class: 'btn btn-default btn-sm' %>
                    <%= link_to '変更', edit_appl_path(appl), class: 'btn btn-primary btn-sm' %>
                    <%= link_to '削除', appl, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn btn-danger btn-sm' %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
          <ul class="pagination pagination-sm no-margin pull-right">
            <li><a href="#">«</a></li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">»</a></li>
          </ul>
        </div>
        <!-- /.box-footer -->
      </div>
      <!-- /.box -->
    </div>
  </div>
</section>
<!-- /.content -->

approvalsys/app/views/appls/new.html.erb
<section class="content-header">
  <h1>Appl作成</h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
    <li class="active">Here</li>
  </ol>
</section>
<%= render 'form', appl: @appl %>

approvalsys/app/views/appls/show.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Appl表示</h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
    <li class="active">Here</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
  <!--------------------------
     | Your Page Content Here |
    -------------------------->
  <div class="row">
    <div class="col-xs-6">
      <div class="box">
        <div class="box-body table-responsive no-padding">
          <p>
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <%= notice %>
            </div>
          </p>
          <%= notice %>
          <table class="table">
            <tbody>
                              <tr>
                  <td><strong>User:</strong></td>
                  <td><%= @appl.user_id %></td>
                </tr>
                              <tr>
                  <td><strong>Title:</strong></td>
                  <td><%= @appl.title %></td>
                </tr>
                              <tr>
                  <td><strong>State:</strong></td>
                  <td><%= @appl.state %></td>
                </tr>
                              <tr>
                  <td><strong>Description:</strong></td>
                  <td><%= @appl.description %></td>
                </tr>
                          </tbody>
          </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
          <div class="no-margin pull-right">
            <%= link_to '戻る', appls_path, class: 'btn btn-primary' %>
            <%= link_to '変更', edit_appl_path(@appl), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
      <!-- /.box -->
    </div>
  </div>
</section>
<!-- /.content -->